- README.md
Followup to 91eb6c3e and d13eb8d7.
~~Also update go -> Go in fenced code block highlighting (both work, but this is the correct language name case).~~
> Update import path case.

- README.md
- autorest/autorest.go
- autorest/autorest_test.go
- autorest/azure/azure.go
- autorest/azure/azure_test.go
- autorest/client.go
- autorest/client_test.go
- autorest/date/date.go
- autorest/mocks/helpers.go
- autorest/mocks/mocks.go
- autorest/preparer.go
- autorest/preparer_test.go
- autorest/responder.go
- autorest/responder_test.go
- autorest/sender_test.go
- autorest/to/convert.go
- autorest/to/convert_test.go
- autorest/utility_test.go
- autorest/version.go
- autorest/version_test.go
- Added support for User-Agent header
- Changed WithHeader PrepareDecorator to use set vs. add
- Added JSON to error when unmarshalling fails
-Added Client#Send method
- Corrected case of "Azure" in package paths
- Added convert helpers, Azure helpers, and improved ease-of-use
- Corrected golint issues
> -- Added Logging inspectors to trace http.Request / Response

- autorest/azure/example/README.md
- autorest/azure/example/main.go
- autorest/azure/token.go
- autorest/version.go
- autorest/version_test.go
This PR enables the use of certificates to retrieve a service principal auth token.
It replaces `clientSecret` on SPT with a field `secret` which is a struct implementing `ServicePrincipalSecret`. In `Refresh()`, rather than just adding the "client_secret" to the form, we call `ServicePrincipalSecret`'s `SetAuthValues` to modify the form as needed.
`ServicePrincipalTokenSecret` will add `client_secret` to the request.
`ServicePrincipalCertSecret` will add `client_assertion` and `client_assertion_type` to the request. 
It does introduce two new dependencies to `go-autorest`:
* `github.com/dgrijalva/jwt-go`
* `golang.org/x/crypto/pkcs12` (the one Paul just pushed back into x/crypto)
It *could* be possible to avoid those by:
1. Reimplementing the few things needed from `jwt-go`.
2. Requiring …
> Implement certificate based auth for service principal tokens

- CHANGELOG.md
- autorest/to/convert.go
- autorest/to/convert_test.go
All Tags fields actually accept `*map[string]*string` in Azure SDK. (`ack --go Tags | grep -v '^//' | grep map`)
cc: @brendandixon PTAL
> return pointer from to.StringMapPtr

- CHANGELOG.md
- autorest/azure/example/main.go
- autorest/azure/token.go
ServicePrincipalCertificateSecret was overly pkcs12-specific. As it turns out, KeyVault requires a PKCS12 but places them on box as PKCS8.
This change makes ServicePrincipalCertificateSecret more generic. It also updates the example to decode the pkcs12 certificate and then use ServicePrincipalCertificateSecret as expected.
> remove pkcs12 support, add generic cert support

- autorest/to/convert.go
- autorest/to/convert_test.go
Azure Go SDK makes use of `*[]string` type in various models.
[`arm/network.AddressSpace`][1] is an example. Adding helper methods to
handle conversion of string slices to pointers and vice versa.
Signed-off-by: Ahmet Alp Balkan
cc: @brendandixon 
[1]: https://github.com/Azure/azure-sdk-for-go/blob/master/arm/network/models.go#L440
> Add StringSlice/StringSlicePtr

- autorest/responder.go
- autorest/utility.go
- autorest/utility_test.go
@ahmetalpbalkan @colemickens 
I factored out code previously used by ByUnmarshallingJSON and ByUnmarshallingXML into helpers. Doing so replaces the magic strings with constants and provides a CopyAndDecode helper useful in other situations.
> Created NewDecoder and CopyAndDecode helpers

- autorest/client.go
Little idiomatic change, should not have any semantic difference at all.
> Use http.DefaultClient instance

- autorest/autorest.go
- autorest/autorest_test.go
Fixes https://github.com/Azure/azure-sdk-for-go/issues/264.
> Add response inspection for polling response

- autorest/azure/example/main.go
- autorest/client.go
- autorest/client_test.go
Breaking change. This will require changing the call to `Send()` in the auto-generated SDK.
> Removing codes... from Send()

- autorest/azure/azure.go
- autorest/azure/azure_test.go
@brendandixon/@colemickens,
I took a stab at handling the Azure error responses specifically to allow them to be deserialized and surfaced to the caller in a nice, type-safe way. An Azure service error response looks like this:
```json
{
"error": {
"code": "LocationRequired",
"message": "The location property is required for this definition."
}
}
```
Logic is as follows:
* if statuscode=4xx or 5xx:
* read the response body (and close) and unmarshal into `*AzureError` type.
* if `*AzureError` looks alright: return it
* otherwise: let the next decorator run
Downsides:
* the next decorator won't have the resp.Body anymore (such as WithErrorUnlessStatusCode will be returning a closed resp.Body)
* will work if Azure always returns this kind of a response.
Please let me know what you think. …
> Add responder for Azure-specific errors

- autorest/autorest.go
- autorest/azure/token.go
- autorest/client.go
- autorest/error.go
- autorest/error_test.go
- autorest/responder.go
- autorest/sender.go
In cases where resp would be nil (such as net.Dial failures) code
in azure sdk et al. just panics with nil dereference error.
I am making NewErrorWithError take an *http.Response instead of
status code and handling nil of this argument internally.
Also removed NewErrorWithStatusCode and added NewErrorWithResponse
for cases where inner error does not exist.
> Fix nil dereference panic in NewErrorWithError when resp=nil

- autorest/client.go
- autorest/client_test.go
We were too aggressive in removing the Body closure when Send returns an error. If Send returns an unmanufactured error (e.g., network failure), we should close the Response Body any time the Body is non-nil.
> Re-adding code to close Response Body if Sending returns an error

- autorest/azure/azure.go
- autorest/azure/azure_test.go
- autorest/error.go
- autorest/error_test.go
Restructured Azure and Autorest errors to ensure they are not unnecessarily wrapped.
> Ensured Azure service errors are unwrapped

- autorest/azure/example/main.go
- autorest/azure/persist.go
- autorest/azure/persist_test.go
- I noticed we're using math/rand without seeding to create a temp file.
In case of multiple writers, they will create the same file path and
will corrupt that tmp file, hence defeat the purpose. Replaced that
with ioutil.TempFile, which is designed for this purpose.
- Added mode argument to SaveToken as tokens were saved under 0644
mode which can be read by all users on the system. This lets setting
perms such as 0600.
- TestSaveTokenFailsCantCreate was testing the wrong predicate. Fixed.
cc:@colemickens
> azure: Fix issues with persist logic

- autorest/azure/devicetoken.go
- autorest/azure/devicetoken_test.go
- autorest/azure/example/main.go
- autorest/azure/token.go
- autorest/azure/token_test.go
This PR is meant to address issues affecting the reliability of device auth flow across a variety of scenarios (various combinations of apps, app owners, tenants, org/personal accounts).
This makes the device token auth flow a bit more generic. I was going to implement an alternative approach, but this is actually fine. The consumer can do what they like:
1. If they were, say interested in creating a really user friendly tool that didn't require knowledge of a subscriptionID ahead of time, they can get a `common` access tokens, list tenants, and refresh the `common` access token for a `tenant-specific` access token.
2. On the other hand, if the consumer knows `tenantID` they can go directly to the correct authority and skip the refresh orchestration (which is what was suggested to us by …
> Allow user to specify tenant id during device flow

- CHANGELOG.md
- autorest/autorest.go
- autorest/autorest_test.go
- autorest/azure/azure.go
- autorest/azure/azure_test.go
- autorest/client.go
- autorest/client_test.go
- autorest/date/date.go
- autorest/date/date_test.go
- autorest/date/time.go
- autorest/date/time_test.go
- autorest/mocks/helpers.go
- autorest/preparer.go
- autorest/responder.go
- autorest/responder_test.go
- autorest/utility.go
- autorest/utility_test.go
- autorest/version.go
- autorest/version_test.go
Added RepondDecorators to unmarshall primitive types
Corrected invocation of Prepare inspector / authorizer
> Added RepondDecorators to unmarshall primitive types

- autorest/azure/config.go
- autorest/azure/devicetoken.go
- autorest/azure/devicetoken_test.go
- autorest/azure/environments.go
- autorest/azure/environments_test.go
- autorest/azure/example/main.go
- autorest/azure/token.go
- autorest/azure/token_test.go
new types: 
* OAuthConfig (represents the three oauth endpoints, tenant-specific) 
* Environment (represents the various endpoints for an azure cloud [public, usgov, china]).
After this change, SPT doesn't know about tenant-id (an Azure specific thing) and instead takes an "OAuthConfig" with urls that are already tenant-specific as the user requests. This makes our client more similar to other OAuth clients. See the `example.go` to see how this changes usage.
This is breaking change, but it's also needed to support anything other than the Azure public cloud.
> Add Azure Environments; Use OAuthConfig throughout

- autorest/azure/token.go
This is needed to acquire access tokens to different `resource`s without re-initializing the auth flow each time. (Not so important for clientsecret/cert auth, but very important for device flow).
> azure/token.go: Add RefreshExchange for Azure

- CHANGELOG.md
- autorest/autorest.go
- autorest/autorest_test.go
- autorest/azure/async.go
- autorest/azure/async_test.go
- autorest/azure/azure.go
- autorest/azure/azure_test.go
- autorest/azure/devicetoken.go
- autorest/azure/devicetoken_test.go
- autorest/azure/example/main.go
- autorest/azure/token_test.go
- autorest/client.go
- autorest/client_test.go
- autorest/mocks/mocks.go
- autorest/preparer.go
- autorest/preparer_test.go
- autorest/sender.go
- autorest/sender_test.go
- autorest/utility_test.go
- autorest/version.go
- autorest/version_test.go
This PR *significantly* changes how `go-autorest` handles polling. By using `SendDecorators` it can now address specific cases (such as handling Azure long-running operations).
> Reworked handling asynchronous and polled requests

- autorest/azure/persist.go
Fixes the
"The process cannot access the file because it is being used by another process." 
issue on windows.
@colemickens
> Close temp file on token persist

- CHANGELOG.md
- autorest/azure/async.go
- autorest/azure/async_test.go
- autorest/azure/azure_test.go
- autorest/client.go
- autorest/date/time.go
- autorest/mocks/helpers.go
- autorest/mocks/mocks.go
- autorest/responder.go
- autorest/responder_test.go
- autorest/utility.go
- autorest/utility_test.go
- autorest/version.go
- autorest/version_test.go
Removed type-specific unmarshalling code; reverted to using ```json.Unmarshal```.
Added ```ByCopying``` responder with supporting ```TeeReadCloser```.
Rewrote Azure asynchronous handling
> Correct handling of malformed JSON and polling for Azure asynchronous operations

- CHANGELOG.md
- autorest/azure/async.go
- autorest/azure/async_test.go
Corrected DoPollForAsynchronous to use the first discovered polling method.
> Corrected DoPollForAsynchronous

- autorest/autorest_test.go
- autorest/azure/async_test.go
- autorest/azure/azure_test.go
- autorest/azure/devicetoken_test.go
- autorest/azure/environments_test.go
- autorest/azure/persist_test.go
- autorest/azure/token_test.go
- autorest/client_test.go
- autorest/date/date_test.go
- autorest/date/time_test.go
- autorest/date/timerfc1123_test.go
- autorest/error_test.go
- autorest/preparer_test.go
- autorest/responder_test.go
- autorest/sender_test.go
- autorest/to/convert_test.go
- autorest/utility_test.go
- autorest/version_test.go
t.Error continues execution for the rest of the test and often
relies on miscomputed values etc, whereas t.Fatal returns from
the test case right away.
t.Fatal fits better in our use case as we compute-and-use
in our use case rather than exercising a set of test inputs.
> Replace t.Error with t.Fatal

- autorest/azure/persist.go
- autorest/client.go
- autorest/client_test.go
- autorest/responder.go
- autorest/sender.go
Some cleanup:
- Fixed a bug in persist.go with missing error check
- DelayForBackoff was unnecessarily using an error type
and was allocating a channel when nil ch would do just fine
- Fixed some eager mock-response closings and added error checks
previously shadowing the body copying errors.
Signed-off-by: Ahmet Alp Balkan <ahmetalpbalkan@gmail.com>
> Refactoring for unchecked errors

- CHANGELOG.md
- autorest/azure/async.go
- autorest/azure/async_test.go
Fixed for issue [#328](https://github.com/Azure/azure-sdk-for-go/issues/328).
> Add check to start polling when status codes is in (200,201,202).

- autorest/azure/persist.go
- autorest/azure/persist_test.go
I had a couple of instances where token renewal failed to replace to persisted token. There error message was "file is in use". It checked with procexp to see what was holding the file open and it turns out to be the same process. I tracked it down to here.
Also made the tests work on Windows...
> Fix 'file in use' issue when renewing token in devicetoken flow

- autorest/azure/async.go
I think @garimakhulbe was making this change as part of a larger PR, but I'm sending this so that I can vendor it now for the PR I'm preparing for Kubernetes. This change saves me upwards of a minute or two whenever provisioning external load balancers for Kubernetes Services. I've been running this code for a while as-is; works as intended.
> Fix for #58: Store RetryAfter for subsequent requests

- autorest/azure/async_test.go
- autorest/azure/azure.go
- autorest/azure/azure_test.go
- autorest/error.go
Fix sdk issue [#339](https://github.com/Azure/azure-sdk-for-go/issues/339). Code to decode "details:" in service error when present.
```
error:
code:
message:
**details:[]**
```
> update azure error for detailed error

- autorest/azure/environments.go
- autorest/azure/environments_test.go
Add serialization for the Environment type based on the style of the
Azure/azure-sdk-for-go library.  One could already serialize the types,
but this makes it explicit, and in our approved style.
Closes #72
> Serialization of Environment

- autorest/azure/example/main.go
- autorest/client.go
- autorest/mocks/helpers.go
- autorest/mocks/mocks.go
- autorest/preparer.go
- autorest/preparer_test.go
- autorest/sender.go
- autorest/sender_test.go
- autorest/utility.go
- autorest/utility_test.go
- Add retry logic for 408, 500, 502, 503 and 504 status codes.
- Add CookieJar in Client.
- Change url path and query encoding logic.
- Fix DelayForBackoff for proper exponential delay.
> Add decorator DoRetryForStatusCodes for retry logic. Add CookieJar.

- autorest/azure/environments.go
- autorest/azure/environments_test.go
I need this too, so I thought to make it a helper in autorest/azure.
Rather than being so lenient, it expects exact values.
Curious about:
1. If these are the exact values we want (again, I contend we need to get ARM/someone to publish an exact guideline for this).
2. If we want to fix noun/adjective agreement
3. If we want to treat empty string as public cloud? Or if that should just be handled by caller.
CC: @boumenot @ahmetalpbalkan @paulmey
> azure: add EnvironmentFromName

- autorest/validation/validation.go
- autorest/validation/validation_test.go
This code will check null, empty or other validations on input parameters. SDK will pass validation array to go-autorest Validate() method which will check listed validations on parameter value using reflect package.
For example, if ```CreateOrUpdate() ```method has resource group and subscription as required parameters, then it will call ```Validate()``` on```[]autorest.Validation``` like below...
```Go
func (c client) CreateOrUpdate(resourceGroupName string, subscriptionID string) (result, error) {
if err := autorest.Validate([]autorest.Validation{
{client.SubscriptionID,
[]autorest.Constraint{{"subscriptionID", "Empty", true, nil}}},
{resourceGroupName,
[]autorest.Constraint{{"resourceGroupName", "Empty", true, nil},
{"resourceGroupName", "MaxLength", 10, nil},
{"resourceGroupName", …
```
> Add code for parameter validation

- .travis.yml
- CHANGELOG.md
- autorest/validation/validation.go
- autorest/validation/validation_test.go
Added field names in parameter in validation struct. ```parameters.Properties.AutoStorage.StorageAccountID```
It will now look like below...
```Go
{resourceGroupName,
[]validation.Constraint{{"resourceGroupName", validation.Pattern, `^[-\w\._]+$`, nil}}},
{accountName,
[]validation.Constraint{{"accountName", validation.MaxLength, 24, nil},
{"accountName", validation.MinLength, 3, nil},
{"accountName", validation.Pattern, `^[-\w\._]+$`, nil}}},
{parameters,
[]validation.Constraint{{"parameters.Properties", validation.Null, false,
[]validation.Constraint{{"parameters.Properties.AutoStorage", validation.Null, false,
[]validation.Constraint{{"parameters.Properties.AutoStorage.StorageAccountID", validation.Null, true, nil}}},
}}}}}); err != nil {
```
Errors will be... …
> Reformat validation error for better error message.

- glide.lock
- glide.yaml
Added package testify in glide.yaml.
When I did ```glide up```, it added some test imports in lock file(assuming for testify). I removed these tests imports to keep lock file clean and they are not affecting go-autorest code anyway.
```Go
hash: e9be0ae2ba50b38578ec6b497b908924851ece4a9f796714bae46327e25b9ae9
updated: 2016-08-31T11:13:52.9423908-07:00
imports:
- name: github.com/dgrijalva/jwt-go
version: f0777076321ab64f6efc15a82d9d23b98539b943
subpackages:
- .
- name: github.com/stretchr/testify
version: d77da356e56a7428ad25149ca77381849a6a5232
repo: https://github.com/stretchr/testify.git
vcs: git
subpackages:
- assert
- require
- name: golang.org/x/crypto
version: f3241ce8505855877cc8a9717bd61a0f7c4ea83c
repo: https://github.com/golang/crypto.git
vcs: git
subpackages:
- pkcs12
- …
```
> Add package testify in glide.yaml

- autorest/azure/token_test.go
- autorest/client_test.go
As reported in #83, there are some tests that are accessing the network, which is a policy violation in Debian, and in general not a good idea. This PR fixes two of these tests.
Please note that there is another test in token_test.go (TestServicePrincipalTokenWithAuthorizationReturnsErrorIfCannotRefresh) that is also accessing the network but I was not able to fix, as I don't really know the autorest API, I am just the Debian maintainer :-)
> Prevent tests from accessing the network.

- autorest/date/time.go
Some APIs don't fully comply with RFC3339 and omit the time zone suffix
which breaks unmarshaling.  To work around this I have added another
formatting for time parsing that omits the suffix.
Ideally the APIs should return proper RFC3339 time information, will
follow up on this separately.
> Fix parsing of UTC times that are not RFC3339 conformant.

- autorest/date/time.go
- autorest/date/time_test.go
- glide.lock
- glide.yaml
The change made in commit 55719cb didn't account for positive or negative
offsets, this change fixes that.  Added test coverage for this scenario.
> Fix UTC time parsing when an offset is specified.

- autorest/azure/token.go
Currently, the token API is failing for cert based secrets. The failure is because of invalid aud claim. Fixing audience (aud) claim to have string value, rather than URL object
> AUD Claim Fix to have string value

- autorest/azure/persist_test.go
- autorest/azure/token_test.go
Fixed hard-coded assumption on windir being "c:\windows".
The test "TestSaveTokenFailsCantCreate" now passes on Windows OS.
Fixed token test to use a mock so it doesn't hit the network.
> Fix for a few test bugs.

- autorest/azure/token.go
- autorest/error.go
- autorest/responder.go
- autorest/responder_test.go
Adding responder which can deal with both success and error response. This will also help to consolidate usage of response.Body at one place. Depending on API result, response body is unmarshalled to either success type or error type.
> New responder to unmarshal success or error response at one place.

- autorest/sender.go
Passing 1 to DelayForBackoff results in the delay being doubled. If a delay
of 1 minute is used, it is unexpected that the polling delays for 2
minutes.
Encountered while debugging https://github.com/kubernetes/kubernetes/issues/35180#issuecomment-273085063
> Pass attempt 0 to DelayForBackoff in AfterDelay

- autorest/azure/environments.go
is "?version-api" a leftover from some older server version deployed ? it doesn't work for me in China - see https://github.com/hashicorp/terraform/issues/11131
> Fixing terraform's issue #11131

- autorest/client.go
- autorest/client_test.go
- autorest/version.go
- autorest/version_test.go
An example user agent looks like this...
```
Go/go1.7 (amd64-windows) go-autorest/7.2.2
```
Another example. When using ARM packages in the Azure SDK for Go, the user agent would look like this...
```
Go/go1.7 (amd64-windows) go-autorest/7.2.2 Azure-SDK-for-Go/7.0.1-beta arm-resources/2016-09-01
```
Just like in the [Ruby SDK](https://github.com/Azure/azure-sdk-for-ruby/pull/543), users can also add more info with `AddToUserAgent`.
PTAL
@kirthik @salameer @jhendrixMSFT @marstr @vishrutshah
> Adding telemetry

- autorest/version.go
- autorest/version_test.go
- glide.lock
- glide.yaml
For the v7.2.3 release, the autorest.Version() function didn't get
updated to reflect the new release. To ensure that doesn't happen again,
the TestVersion() function was updated to make sure that when commited,
the version is greater than the most recently relesed version.
This added a tight coupling with Git and using tags as release
mechanisms.
> Updating Version() test to assert it is updated

- autorest/responder.go
Fixes [this issue](https://github.com/Azure/go-autorest/issues/109).
PTAL @marstr @jhendrixMSFT
> Remove UTF-8 BOM from response body

- CHANGELOG.md
- README.md
- autorest/autorest.go
- autorest/azure/async.go
- autorest/azure/async_test.go
- autorest/responder.go
- autorest/responder_test.go
- autorest/sender.go
- autorest/sender_test.go
- autorest/version.go
This issue is detailed in #117
> Adding ByDiscardingBody() decorator.

- autorest/preparer.go
- autorest/preparer_test.go
- autorest/version.go
- autorest/version_test.go
This is for `x-ms-parametrized-host` support.
PTAL @jhendrixMSFT @marstr
> Added WithCustomBaseURL func

- autorest/version.go
This will match the auto-generated ARM `Version()` functions in [Azure/azure-sdk-for-go](https://github.com/Azure/azure-sdk-for-go). Also, it helps employ the type system to prevent people from shooting themselves in the foot when updating the reported version.
> Fixing a personal nit in the Version() function.

- .travis.yml
Several of our partners have upgraded to use Go 1.8. In order to support
them, CI should do this.
https://beta.golang.org/doc/go1.8
> Updating CI to use Go 1.8.

- autorest/azure/async.go
- autorest/azure/async_test.go
When available, there is no reason not to re-use constant values from stdlib.
> Cleaning up redundant consts.

- .travis.yml
- autorest/adal/config.go
- autorest/adal/example-msi-app/.gitignore
- autorest/adal/example-msi-app/README.md
- autorest/adal/example-msi-app/build-and-upload.sh
- autorest/adal/example-msi-app/main.go
- autorest/adal/example-msi-app/test.sh
- autorest/adal/token.go
- autorest/adal/token_test.go
This stacks on top of #122, please just look at the last commit.
I can't decide if it should be `NewServicePrincipalTokenFromMSI` or if it should be `NewServicePrincipalTokenFromMSIExtension`...
If it's the former, then in the future, it has to try to detect whether to use extension endpoint+api or the future endpoint+api.
If it's the latter, then in the future, application code has to be updated, rather than just updating the SDK to take advantage of MSI in the new endpoint.
> adal: add support for MSI VM Extension

- autorest/date/unixtime.go
- autorest/date/unixtime_test.go
In support of Azure/azure-sdk-for-go#587, I've implemented UnixTime for marshaling and unmarshaling Swaggers that include Unix Timestamps. Next will be updating the generator to recognize this as a well-known type.
> Finished Text, Binary, and JSON for UnixTime

- autorest/error.go
Adding a copy of the Response that was received as the failure occurred. That way we can read Headers and such as part of the error response instead of pulling up Fiddlr.
> Adding http.Resonse to error so Headers can be read.

- autorest/retriablerequest.go
- autorest/sender.go
The current retry logic always makes a copy of the request body by calling
ioutil.ReadAll() which is inefficient in some cases.  This change moves
the handling of the request body into type RetriableRequest and implements
a few different stratagies for preserving the request body.
> Add type RetriableRequest to wrap retrying an HTTP request.

- .travis.yml
- autorest/retriablerequest.go
Now that Go 1.7 has been removed from CI we can enable this
optimization that relies on GetBody() which was added in 1.8.
> Uncomment retry logic codepaths that depend on Go 1.8.

- .travis.yml
- autorest/date/unixtime_test.go
- autorest/retriablerequest.go
- autorest/retriablerequest_1.7.go
- autorest/retriablerequest_1.8.go
Moved version-specific code to source files with appropriate build tags
and added earlier versions of Go to travis CI.
Exclude the unixtime tests from 1.6 as they rely on functionality that
isn't available in 1.6.
> Make RetriableRequest work with multiple versions of Go.

- autorest/authorization.go
- autorest/authorization_test.go
- autorest/retriablerequest_1.7.go
- autorest/retriablerequest_1.8.go
Creation of bearer authorization requires the tenant ID and resource URL
and in some cases it can be tricky to obtain the correct values leading
to authentication failures.  To simplify this we can rely on the bearer
authorization header to obtain the correct tenant ID and resource URL,
providing these bits of data via an authorization callback that's
invoked when a request is submitted.
> Add support for bearer authentication callbacks.

- .gitignore
- autorest/adal/cli_token.go
- autorest/adal/persist.go
- glide.lock
- glide.yaml
Both the Node.JS and Python Azure CLI's store the authentication tokens generated from `az(ure) login` in `~/.azure/accessTokens.json`.
Attempting to load this file using `adal.LoadToken()` fails due to there being multiple Tokens within a single file with a different schema - as such I've added a new method to load the tokens out of the file generated by the Azure CLI.
I've tested this on macOS with multiple subscriptions associated with the Azure account and this seems to work, but I'm unaware of if the file contents is different for users with a single subscription on the account?
> Support for parsing the Tokens out of the Azure CLI AccessTokens file

- autorest/adal/cli.go
- autorest/adal/persist.go
- glide.lock
- glide.yaml
This PR adds support for parsing the list of profiles out of the Azure CLI files. Unfortunately the file written by the Python CLI writes a UTF8BOM at the start of the file, which the built-in JSON parser isn't so happy about and as such we need to filter the request out first; hence why I've brought in github.com/dimchansky/utfbom (which is licensed under Apache2)
> Support for parsing the list of profiles from the Azure CLI entries

- autorest/azure/azure.go
- autorest/azure/azure_test.go
Should solve problem described here: https://github.com/Azure/azure-sdk-for-go/issues/748
The problem is that result of API call is ServiceError itself, not ServiceError wrapped in error object. Which causes autorest to return 'Unknown' error instead.
Fixes: 748
> Added support for unwrapped Azure API error responses

- autorest/azure/async.go
- autorest/azure/async_test.go
This change adds exported type Future which will be used by generated
response types for long-running operations.  It allows the caller to
track the status of a LRO and implement their own polling mechanism.
It builds on the existing and well-tested LRO infrastructure.
> Add type Future used to track status of long-running operations.

- CHANGELOG.md
- autorest/azure/rp.go
Errors that were not about the RP registration were not being shown.
PTAL @marstr @jhendrixMSFT @vladbarosan 
> More complete error

- autorest/azure/async.go
- autorest/azure/async_test.go
Some long-running operations will return a Retry-After response header
indicating how long a client should wait before checking the status.
Add a method exposing this information when present.
> Add method GetPollingDelay to Future.

- CHANGELOG.md
- autorest/azure/async.go
- autorest/azure/async_test.go
- autorest/utility.go
Make the type of polling used available to callers; this is required to
know if the end of a LRO requires an additional GET or not.
Add helper function ChangeToGet() to be used when retrieving the final
result of certain long-running operations.
> Add method PollingMethod() to Future.

- CHANGELOG.md
- autorest/sender.go
Retry when sender.Do returns a non-nil error.
> DoRetryForStatusCodes will retry on transient failures.

- .travis.yml
- CHANGELOG.md
- autorest/autorest.go
- autorest/azure/async.go
- autorest/azure/async_test.go
- autorest/client.go
- autorest/mocks/mocks.go
The WaitForCompletion method provides a default implementation that will
wait until a future has completed, is cancelled or times out.
> Add WaitForCompletion to Future type.

- CHANGELOG.md
- autorest/azure/cli/token.go
1. Add logic to read path of access tokens through environment variable.
2. Add fallback logic to default one.
Notice: this is short-term fix and require user to use latest version of provider in Cloud Shell.
> Hotfix: update the logic to get path of access tokens.

- CHANGELOG.md
- autorest/azure/async.go
We have seen a case where the polling state string is all lower case
which caused an infinite loop while polling.
> Use case-insensitive string comparison for polling state.

- autorest/utility.go
- autorest/utility_test.go
> Add support for API calls with non string slice parameters

- CHANGELOG.md
- autorest/azure/rp.go
- autorest/client.go
- autorest/sender.go
- autorest/utility.go
Added field SkipResourceProviderRegistration to the Client struct so
that callers can opt out of automatic RP registration.
When checking for authentication failure look at the error's type
instead of checking a hard-coded list of HTTP status codes.
> Features and fixes for v9.5.

- CHANGELOG.md
- autorest/azure/rp.go
- autorest/azure/rp_test.go
- autorest/sender.go
- autorest/sender_test.go
If an API returns a 429 don't include it in the retry count so that we
can keep retrying until the operation succeeds.
Don't skip retry logic when SkipResourceProviderRegistration is enabled.
> Don't count 429 as a retry attempt.

- CHANGELOG.md
- autorest/sender.go
- autorest/sender_test.go
If we didn't receive a response in the retry loop don't dereference it
and just count it against the retry cap.
> Check for nil response before dereferencing it.

- CHANGELOG.md
- autorest/adal/token.go
- autorest/adal/token_test.go
Added function NewServicePrincipalTokenFromMSIWithUserAssignedID for
creating a token via MSI with a user assigned identity.
Updated comments for NewServicePrincipalTokenFromMSI indicating that it
uses the system assigned identity.
> Add support for MSI-based tokens with a user assigned identity.

- CHANGELOG.md
- autorest/azure/rp.go
When polling for RP registration status use the client object so that
its Do() method is invoked which will add the Authorization header.
> Fix for missing authorization header.

- CHANGELOG.md
- autorest/preparer.go
Added a new preparer decorator for application/octet-streams.
> Add support for application/octet-stream MIME types.

- autorest/azure/async.go
- autorest/azure/azure.go
- autorest/azure/azure_test.go
The data contract for ARM errors includes `innererror` field which is a property bag with unspecified contents as per [OData 4.0 spec](http://docs.oasis-open.org/odata/odata-json-format/v4.0/os/odata-json-format-v4.0-os.html#_Toc372793091). This field wasn't used by ARM up until now, but recently there was a change related to Azure Policy that makes heavy use of this property bag. It is already deployed in all regions and consumed by Azure Portal, so now would be a good time to support it in SDKs as well.
The new errors are generated by the ARM Frontdoor itself, so CloudErrorData seems like the most appropriate contract to include it. This change also adds the optional `target` field which was missing for some reason.
> Add target and innererror fields to ServiceError

- autorest/azure/async.go
- autorest/azure/azure.go
- autorest/azure/azure_test.go
- autorest/azure/rp.go
Some services don't conform to the OData spec, returning a single object
for details instead of an array with one object. Added a custom
unmarshaler to ServiceError to handle both cases.
Fixed the Details field to conform to the spec; this is a breaking
change.
> Fix unmarshalling of ServiceError.

- CHANGELOG.md
- autorest/azure/async.go
This new error type will be returned from generated Result() methods on
generated future types to better distinguish between a future that
hasn't completed vs. some other kind of failure.
> Add new type azure.AsyncOpIncompleteError

- autorest/azure/async.go
- autorest/azure/async_test.go
LROs might return error information in OData v4 format, so change the
pollingState struct to capture the complete ServiceError object.
Updated Future.Done() to return a ServiceError object if the polling
failed and the response contains an error body.
> Extend pollingState to use ServiceError

- CHANGELOG.md
- autorest/azure/async.go
- autorest/version.go
Some LROs can return a 204 as the final response so add it to the list
of expected polling codes.
Updated version info as it's sorely outdated.
> Update LRO polling to accept StatusNoContent (204)

- autorest/validation/error.go
- autorest/validation/validation.go
- autorest/validation/validation_test.go
Added type validation.Error to be returned when validation of an APIs
arguments fails one or more constraints.
> Make validation failures return a unique error type.

- CHANGELOG.md
- autorest/adal/token.go
- autorest/authorization.go
Added type EventGridKeyAuthorizer for key authorization with an event
grid topic.
Fixed a race condition when auto-refreshing service principal tokens.
> Add key authorizer for event grid.

- autorest/adal/cmd/adal.go
- autorest/adal/token.go
- autorest/adal/token_test.go
- autorest/authorization_test.go
- autorest/azure/example/main.go
The previous fix was incomplete as the token could be read outside of
the lock.  Switched to a reader-writer lock for finer-grain access to
the token; this required decomposing Token from ServicePrincipalToken.
This is a breaking change.
> Fix race condition in token auto-refresh.

- autorest/azure/async.go
LROs that return the Location header will use its value for polling and
for retrieving the final result of the LRO.
> Expose the polling URL for futures.

- autorest/validation/validation.go
- autorest/validation/validation_test.go
Add this function back to avoid a breaking change.  The function has
been marked as deprecated and can be removed in the future.
> Add validation.NewErrorWithValidationError() back.

- CHANGELOG.md
- autorest/authorization.go
- autorest/client.go
- autorest/version.go
Preparers are executed in declared order so move the call to
c.WithInspection() to the end of the list so it can inspect any
preceding operations.
Fixed authorizors to call p.Prepare() first so they behave like the
other preparers.
> Fix inspection of authorizors.

- CHANGELOG.md
- autorest/autorest.go
- autorest/azure/async.go
- autorest/azure/async_test.go
- autorest/azure/rp.go
- autorest/azure/rp_test.go
- autorest/sender.go
- autorest/sender_test.go
- autorest/version.go
When polling, use the request's context object instead of the deprecated
Cancel object to see if polling should continue or not.
> Make retry logic use the request's context.

- CHANGELOG.md
- autorest/azure/auth/auth.go
> Pass resource instead off AAD endpoint

- CHANGELOG.md
- autorest/adal/token.go
- autorest/adal/token_test.go
- autorest/authorization.go
- autorest/version.go
Token refresh operations make HTTP requests, thus they should support
contexts so they can be cancelled etc.
Simplified retry logic in refreshInternal().
> Add token refresh operations that take a context

- CHANGELOG.md
- autorest/adal/token.go
- autorest/adal/token_test.go
- autorest/sender.go
- autorest/sender_test.go
- autorest/utility.go
- autorest/version.go
If Do() returns a non-temporary network error don't bother retrying.
Return a TokenRefreshError if the refresh request fails.
> Don't retry on non-temporary network errors.

- CHANGELOG.md
- autorest/adal/token.go
Let me know if this should target master or dev. It would be great to get this out as soon as we can. I'll do my best to mitigate in the Event Hub lib. 
https://github.com/Azure/azure-event-hubs-go/issues/38
This issue only seems to appear when retrying a MSI token.
> response is sometimes nil when error is not nil

- CHANGELOG.md
- autorest/azure/async.go
- autorest/azure/async_test.go
- autorest/mocks/helpers.go
- autorest/mocks/mocks.go
- autorest/version.go
The polling mechanism for async operations is determined by the verb of
the originating request along with the HTTP status code of the initial
response; the original implementation didn't take this into account
which caused some Future types to incorrectly poll or obtain the wrong
URL for retrieving the result.
This change introduces the pollingTracker interface as an abstraction
over verb-specific polling trackers; this allows the logic to be
separated per tracker.  All shared state and methods are in the
pollingTrackerBase type.
> Future state machine rewrite.

- CHANGELOG.md
- autorest/adal/token.go
- autorest/sender_test.go
- autorest/utility.go
- autorest/utility_test.go
- autorest/version.go
Fixed retry logic to use exponential backoff per retry guidelines.
Added StatusGone to the list of IMDS-specific retry status codes.
Changed IsTemporaryNetworkError to be conservative, so errors that don't
implement the net.Error interface are now considered temporary.
> IMDS retry logic should use exponential backoff.

- CHANGELOG.md
- autorest/adal/token.go
- autorest/adal/token_test.go
- autorest/version.go
When refreshing a token obtained via a web app the client_secret field
must be set in the request body.
> Fix refreshing a refresh token from authorization code.

- CHANGELOG.md
- autorest/adal/config.go
- autorest/adal/token.go
- autorest/adal/token_test.go
- autorest/version.go
Most ServicePrincipalToken types can now be marshalled and unmarshalled
to/from JSON, allowing them to be persisted etc.
Added method ServicePrincipalToken.SetRefreshCallbacks() so that refresh
callbacks can be added to unmarshalled SPTs (or updated in general).
Moved methods to be next to their types (no functional changes).
> Add support for marshalling/unmarshalling ServicePrincipalTokens

- CHANGELOG.md
- autorest/adal/token.go
- autorest/adal/token_test.go
- autorest/version.go
Add a new function so an SPT can be created with a current token and
secret.
I am opening against master as opening this against the dev branch pulls in a lot of other commits. 
FIxes https://github.com/Azure/go-autorest/issues/283
> Add function to create new SPT with token and secret

- CHANGELOG.md
- autorest/validation/validation.go
- autorest/validation/validation_test.go
- autorest/version.go
Ensure that integer validation can handle int and int64.
> Validation code handles int and int64

- CHANGELOG.md
- autorest/adal/token.go
- autorest/azure/azure.go
- autorest/azure/azure_test.go
- autorest/azure/rp.go
- autorest/version.go
In IMDS retry logic, if we don't receive a response don't retry.
For error response bodies that aren't OData-v4 compliant stick the raw
JSON in the ServiceError.Details field so the information isn't lost.
Removed superfluous wrapping of response error in
azure.DoRetryWithRegistration.
> Various bug fixes.

- CHANGELOG.md
- autorest/azure/async.go
- autorest/azure/async_test.go
- autorest/version.go
If an LRO returns http.StatusOK on the initial response with no async
headers return the response body from Future.GetResult().
If there is no "final GET URL" return an error.
> Fix panic in LRO implementation

- autorest/azure/azure.go
- autorest/azure/azure_test.go
'additionalInfo', a new property added to ARM error contract, contains additional error information. For example, it will contain detailed policy violation error information when the request to ARM failed due to violation of Azure policies.
The changes are to allow deserializing additionalInfo in ARM error.
> Add additionalInfo to CloudError

- CHANGELOG.md
- autorest/adal/token.go
- autorest/version.go
Added field MaxMSIRefreshAttempts to ServicePrincipalToken with a
default value of five.  Removed hard-coded cap of five attempts.
> Make refreshing MSI tokens have configurable cap

- CHANGELOG.md
- autorest/adal/token.go
- autorest/client.go
- autorest/client_test.go
- version/version.go
Add the standard go-autorest user-agent string to token requests.  This
required moving version info to its own package to avoid a circular
dependency.
> Include user-agent info in token requests

- CHANGELOG.md
- autorest/client.go
- logger/logger.go
- logger/logger_test.go
- version/version.go
Request and response logging can now be enabled by setting the
environment variable AZURE_GO_SDK_LOG_LEVEL.  See the notes in the
change log for more information.
This logger is general-purpose so other data can be logged as required.
> Add support for request/response logging

- CHANGELOG.md
- autorest/azure/async.go
- autorest/azure/async_test.go
- version/version.go
If an LRO returns a failure in the initial response return an error
object at that point so the caller doesn't have to poll.
For failed LROs without an OData v4 error include the response body in
the error's AdditionalInfo field to aid in diagnosing the failure.
> Fixes for LROs

- CHANGELOG.md
- autorest/azure/async.go
- version/version.go
Always initialize the polling URL and method, favoring the
Azure-AsyncOperation header.  Each tracker will update the values as
required.
> Init LRO polling URL and method

- .gitignore
- autorest/azure/auth/auth.go
- autorest/azure/auth/auth_test.go
This enables resource like KeyVault and Container Registry to use an authorizer configured from a configuration file.
> Allow a new authorizer to be created from a configuration file by specifying a resource instead of a base url.

- CHANGELOG.md
- autorest/azure/async.go
- autorest/azure/async_test.go
- version/version.go
If a polling operation returns a failure status code return the
associated error.
> LRO fix for polling failure

- CHANGELOG.md
- autorest/sender.go
- autorest/sender_test.go
- version/version.go
If the request's context is cancelled return the last response.
> Return response when request is cancelled

- CHANGELOG.md
- autorest/adal/token.go
- autorest/adal/token_test.go
See https://tools.ietf.org/html/draft-ietf-jose-json-web-key-41#section-4.7 for the `x5c` header description
AAD allows authentication based on certificate Issuer and Subject Name like in
https://github.com/AzureAD/azure-activedirectory-library-for-dotnet/blob/0c6d6fd76c707b6132e4bc20cd2e71622907d0c6/adal/src/Microsoft.IdentityModel.Clients.ActiveDirectory/Internal/ClientCreds/JsonWebToken.cs#L212
- [N/A] I've added Apache 2.0 Headers to the top of any new source files.
- [N/A] I'm submitting this PR to the `dev` branch, except in the case of urgent bug fixes warranting their own release.
IMHO, this warrants …
> Add the x5c header for certificate issuer + subject name auth

- autorest/azure/auth/auth.go
- autorest/azure/cli/token.go
This PR adds the `NewAuthorizerFromCli` Authorizer factory method, which uses Azure CLI to obtain an access token for the currently logged in user. The implementation is inspired by the [Azure SDK for .NET implementation](https://github.com/Azure/azure-sdk-for-net/blob/b38512ff94eb22446b925f6af2c2bc73207c55a4/src/SdkCommon/AppAuthentication/Azure.Services.AppAuthentication/TokenProviders/AzureCliAccessTokenProvider.cs). These changes would resolve https://github.com/Azure/azure-sdk-for-go/issues/2610.
I've tested the changes on Windows 10 (1803) and Ubuntu 16.04 (through WSL).
There are currently no additional test, because they would depend on an Azure CLI installation with a logged in user. I'm not sure how to mock this, so any pointers are really appreciated if the tests are necessary.
> Authorizer which uses Azure CLI to obtain the token

- .travis.yml
- CHANGELOG.md
- autorest/azure/async.go
- version/version.go
When creating a future always include the polling tracker even if
there's a failure; this allows the underlying response to be obtained
by the caller.
> Fix azure.NewFutureFromResponse to always return tracker

- CHANGELOG.md
- autorest/azure/async.go
- version/version.go
Reference Issue: #318
When HTTP response status is NoContent (204) ContentLenght of the HTTP response is -1. Code checks if ContentLenght != 0 then tries to parse the response, which fails in case ContentLength is -1. 
I modified the code to parse response only if ContentLenght > 0
> Handle ContentLength equals -1 case

- CHANGELOG.md
- autorest/client.go
- autorest/client_test.go
- autorest/version.go
- version/version.go
The version package has been deprecated, superseded by content in the
autorest package.  This is in preparation for implementing modules.
> Deprecate the version package

- CHANGELOG.md
- autorest/azure/auth/auth.go
- autorest/version.go
Added method `ServicePrincipalToken()` to `DeviceFlowConfig` so callers
can obtain the underlying token.
> Add method to obtain SP token from device flow

- CHANGELOG.md
- autorest/azure/async.go
- autorest/azure/async_test.go
- autorest/version.go
For an LRO PUT operation the final GET URL was incorrectly set to the
Location polling URL in some cases.
> Fix final GET for LRO PUT operations

- CHANGELOG.md
- autorest/adal/token.go
- autorest/adal/version.go
- autorest/version.go
Added function adal.AddToUserAgent() to allow callers to append custom
data to the default user-agent header.
Exported adal.UserAgent() for parity with autorest.Client.
> Add ability to update the user-agent header for ADAL

- CHANGELOG.md
- autorest/azure/auth/auth.go
- autorest/azure/auth/auth_test.go
- autorest/version.go
The loading of environment and file settings has been refactored and
exported so that consumers have access to the raw data.
The steps performed in NewAuthorizerFromEnvironment() have been broken
down into methods on EnvironmentSettings so that consumers can build
custom authorization chains.
Added support for certificate authorization for file-based config.
> Refactor auth package to expose settings

- .travis.yml
- CHANGELOG.md
- autorest/adal/persist_test.go
- autorest/client.go
- autorest/version.go
When creating an HTTP client set the minimum version of TLS to 1.2 and
prefer server ciphers.
> Set minimum version of TLS to 1.2

- CHANGELOG.md
- autorest/azure/cli/token.go
- autorest/version.go
GetTokenFromCLI uses shell to launch az when obtaining tokens.
This approach may produce an error under zsh as zsh doesn't always
assume the shell script to be located in /usr/bin.
As the environment variable PATH is set when executing, it can
rely on the shell to locate az CLI script rather than explicitly
specifying the shell.
> Fix GetTokenFromCLI cannot work in zsh

- CHANGELOG.md
- autorest/azure/auth/auth.go
- autorest/version.go
Add methods to obtain a ServicePrincipalToken from file or environment
credential stores.
> More refactoring of the auth package

- CHANGELOG.md
- autorest/client.go
- autorest/version.go
This resolves #379 by using the defaults of http.DefaultTransport without modifying the global object.
> tracing: fix proxy support for default sender (#379)

- CHANGELOG.md
- autorest/client.go
- autorest/client_test.go
- autorest/version.go
- tracing/tracing.go
Related to https://github.com/Azure/go-autorest/issues/384
> add support for TLS Renegotiation

- CHANGELOG.md
- autorest/azure/environments.go
- autorest/azure/environments_test.go
- autorest/azure/testdata/test_environment_1.json
- autorest/version.go
Fix for https://github.com/Azure/azure-sdk-for-go/issues/4234
> Add KeyVaultResourceURL

- autorest/to/convert.go
- autorest/to/convert_test.go
Adding `to.ByteSlicePtr(b []byte)`.  Would love to have this little tool in this great collection.
--- 
> Adding ByteSlicePtr

- autorest/preparer.go
- autorest/preparer_test.go
This PR includes a new Preparer `WithXML` which serializes XML (including the document header) into the HTTP Request
---
> Adding a new `WithXML` method

- autorest/client.go
- autorest/client_test.go
Added IsHTTPStatus() and HasHTTPStatus() methods to autorest.Response
> Add HTTP status code response helpers

- autorest/preparer.go
- autorest/preparer_test.go
Some of [the Storage API's use the HTTP Header `MERGE`](https://docs.microsoft.com/en-us/rest/api/storageservices/insert-or-merge-entity) - since this SDK provides convenience wrappers for other methods - this PR adds a convenience method for the Merge header too.
---
> Adding a new Preparer for the `MERGE` header

- autorest/mocks/helpers.go
- autorest/mocks/mocks.go
- autorest/preparer.go
- autorest/preparer_test.go
- autorest/responder.go
- autorest/responder_test.go
This PR adds a Preparer and a Responder for passing an arbitrary Byte array to the Request, and parsing it from the Response. This is intentionally not using a Reader since the Byte array content is assumed to be coming from specific ranges of a File.
We're using this in the [Get File](https://docs.microsoft.com/en-us/rest/api/storageservices/get-file) and [Put File](https://docs.microsoft.com/en-us/rest/api/storageservices/put-range) endpoints within the Storage SDK we're building that's compatible with Go-Autorest (where I can confirm this works as expected).
---
> New Preparer/Responder for `Unmarshalling Bytes`

- autorest/adal/config.go
- autorest/adal/config_test.go
- autorest/adal/token.go
- autorest/adal/token_test.go
- autorest/authorization.go
- autorest/authorization_test.go
- autorest/azure/auth/auth.go
- autorest/azure/auth/auth_test.go
- autorest/preparer.go
Support for multi-tenant via x-ms-authorization-auxiliary header has
been added for client credentials with secret scenario; this basically
bundles multiple OAuthConfig and ServicePrincipalToken types into
corresponding MultiTenant* types along with a new authorizer that adds
the primary and auxiliary token headers to the reqest.
The authenticaion helpers have been updated to support this scenario; if
environment var AZURE_AUXILIARY_TENANT_IDS is set with a semicolon
delimited list of tenants the multi-tenant codepath will kick in to
create the appropriate authorizer.
> Add support for multi-tenant authentication

- autorest/adal/config.go
- autorest/adal/config_test.go
- autorest/adal/token_test.go
- autorest/azure/auth/auth.go
> rename Options to OAuthOptions

- autorest/go.mod
- autorest/go.sum
Recent change added a dependency on a newer version of the adal module
however the go.mod and go.sum files weren't updated.
> Fix autorest module dependency

- README.md
> Add instructions for how to use with Go modules

- CHANGELOG.md
- autorest/azure/async.go
- autorest/preparer.go
- autorest/preparer_test.go
- autorest/sender.go
- autorest/version.go
Added functions for adding a retrieving one or more PrepareDecorators to
the provided context object.  LRO polling will apply the preparers added
in this way.
WithSendDecorators will ignore empty slices of SendDecorators.
> Add support for custom PrepareDecorator chains

- CHANGELOG.md
- autorest/adal/token.go
- autorest/authorization_test.go
- autorest/version.go
Type MultiTenantServicePrincipalToken didn't fully implement the
RefresherWithContext interface, as a result the type assertion would
always fail in WithAuthorization() and tokens were not retrieved.
> Fix multi-tenant bearer authorization

- CHANGELOG.md
- autorest/preparer.go
- autorest/preparer_test.go
- autorest/version.go
The call to ensureValueStrings() was flattening slices into a string and
as a result multi-value query parameters were malformed.
> Fix WithQueryParameters to properly encode multi-values

- autorest/azure/cli/profile.go
- autorest/azure/cli/token.go
This PR makes `AccessTokensPath()` use `accessTokens.json` from the directory configured by the `AZURE_CONFIG_DIR` environment variable if the `AZURE_ACCESS_TOKEN_FILE` environment variable is not set before falling back on `~/.azure/`.
This matches the behavior of the azure-cli:
- https://github.com/Azure/azure-cli/blob/azure-cli-2.0.73/src/azure-cli-core/azure/cli/core/_profile.py#L879
- https://github.com/Azure/azure-cli/blob/azure-cli-2.0.73/src/azure-cli-core/azure/cli/core/_environment.py#L9
> Use accessTokens.json from AZURE_CONFIG_DIR before falling back on ~/.azure/

- CHANGELOG.md
- autorest/adal/token.go
- autorest/adal/token_test.go
- autorest/sender.go
- autorest/sender_test.go
- autorest/version.go
> Always retry a request even if the sender returns a non-nil error

- CHANGELOG.md
- autorest/adal/token.go
- autorest/adal/token_test.go
- autorest/azure/auth/auth.go
- autorest/version.go
This adds support for the different method of MSI token acquisition on Azure App Service and Azure Functions.
Fixes #447 
> Add MSI for App Service / Functions support

- CHANGELOG.md
- autorest/adal/devicetoken.go
- autorest/adal/devicetoken_test.go
- autorest/version.go
- azure-pipelines.yml
Added functions for device code flow that take a context.
Enforce Go modules mode in CI.
> Add ability to cancel device code flow auth

- autorest/azure/azure.go
- autorest/azure/azure_test.go
- autorest/azure/rp.go
This PR adds support for parsing Errors from Data Plane API's which return XML rather than JSON, by parsing the Content-Type header. Since there's a few different Content-Types for XML (application/xml, text/xml plus some vendor specific ones), I've opted to parse the response as XML if the `Content-Type` contains `xml` - which isn't great but seems better than just passing those two?
This means when a Conflict is returned from the Sender, that HTTP Response:
```
HTTP/1.1 409 The specified container is being deleted. Try operation later.
Content-Length: 252
Content-Type: application/xml
Server: Windows-Azure-Blob/1.0 Microsoft-HTTPAPI/2.0
x-ms-request-id: dcad0bff-301e-00f4-16c7-5949cd000000
x-ms-version: 2018-11-09
x-ms-error-code: ContainerBeingDeleted
Date: Fri, 23 Aug 2019 15:30:39 …
```
> support for parsing error messages from xml responses

- autorest/adal/token.go
All of these methods now take the write lock before running the `refreshInternal`, so these are all safe for concurrent access.
> fix godoc comment for methods that are safe for concurrent use

- autorest/authorization_sas.go
- autorest/authorization_sas_test.go
This commit introduces a new Authorizer for authenticating with Blob Storage using a SAS Token
```
$ go test -v ./autorest/ -run="TestSas"
=== RUN   TestSasNewSasAuthorizerEmptyToken
--- PASS: TestSasNewSasAuthorizerEmptyToken (0.00s)
=== RUN   TestSasNewSasAuthorizerEmptyTokenWithWhitespace
--- PASS: TestSasNewSasAuthorizerEmptyTokenWithWhitespace (0.00s)
=== RUN   TestSasNewSasAuthorizerValidToken
--- PASS: TestSasNewSasAuthorizerValidToken (0.00s)
=== RUN   TestSasAuthorizerRequest
--- PASS: TestSasAuthorizerRequest (0.00s)
authorization_sas_test.go:76: [DEBUG] Testing Case "empty querystring without a prefix"..
authorization_sas_test.go:76: [DEBUG] Testing Case "empty querystring with a prefix"..
authorization_sas_test.go:76: [DEBUG] Testing Case "existing querystring without a …
```
> Adding a new Authorizer for SAS Token Authentication

- autorest/adal/token.go
- autorest/adal/token_test.go
This PR adds support for specifying a custom refresh function which allows users defining manual refresh tokens to refresh the token via a callback
Fixes https://github.com/hashicorp/go-azure-helpers/issues/22
> token: support for a custom refresh func

- CHANGELOG.md
- autorest/utility.go
- autorest/utility_test.go
- autorest/version.go
Hey, how about this solution @jhendrixMSFT? This code accepts interface but casts types not always right. I mean isn't this more correct to cast not only string arrays to string if that function accepts not only strings? If we accept it then we don't need to fix a swagger spec.
realates with https://github.com/Azure/azure-sdk-for-go/issues/6586
> Improve the code to support int and other types and cast them to string

- CHANGELOG.md
- autorest/version.go
v13.3.1 was released however the CHANGELOG and version.go files were not
updated as part of that release.  The files have been updated to
accurately reflect the latest version info.
> Fix CHANGELOG and version info

- autorest/adal/token.go
- autorest/authorization.go
- autorest/azure/async.go
- autorest/sender.go
- autorest/utility.go
- autorest/utility_test.go
The retry helpers and a few other methods weren't reading and closing
response bodies leading to connection leaks.
> Drain response bodies

- autorest/sender.go
> Enable exponential back-off when retrying on 429

- CHANGELOG.md
- autorest/client.go
- autorest/client_test.go
- autorest/version.go
Added field SendDecorators to autorest.Client; this value will be
preferred over the default SendDecorators.
Added method Client.Send() which includes logic for using custom
SendDecorator chains.
> Enable specifying SendDecorators on a client

- CHANGELOG.md
- autorest/sender.go
- autorest/sender_test.go
- autorest/version.go
> Inifinite retries on 429 is no longer the default

- CHANGELOG.md
- autorest/azure/environments.go
- autorest/azure/environments_test.go
- autorest/version.go
Allows modification of the global environments map.
> Add SetEnvironment method to azure package

- CHANGELOG.md
- autorest/authorization.go
- autorest/authorization_test.go
- autorest/version.go
- azure-pipelines.yml
When authenticating across tenants, ARM is using `,` as delimiter of aux tokens as the [docs](https://docs.microsoft.com/en-us/azure/azure-resource-manager/management/authenticate-multi-tenant#header-values-for-authentication) said.
Currently go-sdk uses `;` as delimiter, all requestes send to ARM for more than 2 tenants, will get 401 response.
> Fix `x-ms-authorization-auxiliary` header sperator to comma

- autorest/authorization.go
- autorest/azure/auth/auth.go
This PR
- extracts creation of ServicePrincipalToken for MSI to a public method. The new method can then be used with eg. `denisenkom/go-mssqldb` driver when using Azure authentication to SQL server, like in case of ClientCredentialsConfig or UsernamePasswordConfig.
- adds getter for token provider on BearerAuthorizer so the token can be used for authorization outside the REST in a generic way like, again, together with `denisenkom/go-mssqldb`.
---
> Expose OAuth token provider for use outside autorest

- autorest/azure/environments.go
See from Azurre China portal - this is now cloudapp.chinacloudapi.cn
> Updating resourceManagerVMDNSSuffix for AzureChinaCloud

- CHANGELOG.md
- autorest/azure/async.go
- autorest/azure/async_test.go
- autorest/version.go
If the initial response to an LRO contains a Retry-After header, sleep
for the specified duration before beginning to poll.
> Initial sleep on Retry-After

- CHANGELOG.md
- autorest/azure/environments.go
To fix acctests in `azurerm_api_management` related to https://github.com/terraform-providers/terraform-provider-azurerm/pull/7603.
Environment variables got from service team : https://github.com/Azure/azure-rest-api-specs/issues/10065
> Add `ApiManagementHostManagementSuffix` in environment variables

- autorest/authorization_storage.go
- autorest/authorization_storage_test.go
Well this is a fun one.
After a bunch of debugging it turns out API's in the root of a Storage Data Plane API use a slightly different, undocumented implementation of SharedKey authorization. Specifically [this API](https://docs.microsoft.com/en-us/rest/api/storageservices/set-blob-service-properties) and [this API](https://docs.microsoft.com/en-us/rest/api/storageservices/get-blob-service-properties) - but presumably the others in the root too.
Whilst this is unfortunate - attempting to update this API to [match the definition](https://docs.microsoft.com/en-us/rest/api/storageservices/authorize-with-shared-key) at this point in time would be a breaking change and thus is a less ideal solution.
Instead this PR introduces a new mode to the SharedKey Authorizer which supports the varied …
> auth/storage: support for the SharedKey implementation used by the Storage Accounts Data Plane API

- autorest/authorization_sas.go
- autorest/authorization_sas_test.go
There is a bug preventing requests from being sent when using SAS token authentication because you can't modify the RequestURI.
```
Failure sending request: StatusCode=0
Request.RequestURI can't be set in client requests.
```
Also, when retrying requests, the SAS Token was repeatedly being appended to the query string.
> authorization_sas fixes

- autorest/adal/cmd/adal.go
- autorest/adal/go.mod
- autorest/adal/token.go
- autorest/adal/token_test.go
Allowing 
MSI login with azure resource ID of the userAssignedIdentity is now possible, see "mi_res_id" in this page: 
https://docs.microsoft.com/en-us/azure/active-directory/managed-identities-azure-resources/how-to-use-vm-token#get-a-token-using-http
this PR add new login option with identityResourceID, updated the cmd as well, and I tested all 3 case.
> allow MSI login with "mi_res_id"

- autorest/adal/token.go
- autorest/adal/token_test.go
The presence of the ASE envrionment vars does not indicate that the
caller is actually authenticating in this way.  Instead, look at the
token endpoint URL to see if it matches the ASE endpoint.
> Fix check for App Service Environment

- autorest/adal/cmd/adal.go
- autorest/adal/devicetoken.go
- autorest/adal/persist.go
pkcs12.Decode will fail if a certificate contains more than two safe
bags which is the case for certificates with intermediate authorities.
Switch to using pkcs12.ToPEM, then manually decoding the certificate and
private key blocks.
In CheckForUserCompletionWithContext, return a better error message when
available, falling back to ErrDeviceGeneric.
> Fix decoding of certificates with intermediate CAs

- autorest/mocks/mocks.go
If the request's context has expired return the error.  This allows
mocking of requests that take too long, triggering deadline exceeded.
> Honor the request context in mock sender

- autorest/adal/go.mod
- autorest/adal/go.sum
- autorest/adal/token.go
- autorest/adal/token_test.go
Added adal.MSIAvailable to probe if the MSI endpoint is available.
Return a TokenRefreshError when attempting to authenticate via MSI when
the endpoint isn't available, this will prevent retries from happening.
> Fail-fast if the MSI endpoint is not available

- autorest/azure/auth/auth.go
- autorest/azure/auth/go.mod
- autorest/azure/auth/go.sum
Use adal.DecodePfxCertificateData which handles this properly.
> Fix decoding certificates with intermediate authorities

- autorest/authorization.go
- autorest/authorization_test.go
Make the multi-tenant bearer authorizer publicly available for consumers
that need access to the underlying type.  This also provides symmetry
with the single-tenant bearer authorizer implementation.
> Export multi-tenant bearer authorizer

- autorest/adal/token.go
- autorest/adal/token_1.13.go
- autorest/adal/token_legacy.go
http.NewRequestWithContext() was added in Go 1.13.  This change uses
build constraints to support older versions.
Note that Go 1.7 is the minimum version due to reliance on the context
package.
> Add support for MSIAvailable on older versions of Go

- autorest/adal/token.go
- autorest/adal/token_1.13.go
- autorest/adal/token_legacy.go
- autorest/adal/token_test.go
[This commit](https://github.com/Azure/go-autorest/commit/cbf46deb11b50a1bc9ac059f430c647493829459) allows MSI token acquisition to fail fast. However this flow [swallows the real error](https://github.com/Azure/go-autorest/commit/cbf46deb11b50a1bc9ac059f430c647493829459#diff-104007a705afedbaf9fd03870136bd96R946) unlike the other code paths. This PR bubbles the error up for users.
As `MSIAvailable` is publicly exported, I've avoided changing the external signature and relied on the existing tests. Happy to add some unit tests if you like.
> fix: return error for failed MSI endpoint check

- autorest/preparer.go
- autorest/preparer_test.go
In autorest.WithBaseURL(), encode any query parameters.
> Ensure query parameters are properly encoded

- Gopkg.lock
- Gopkg.toml
- autorest/adal/go.mod
- autorest/adal/go.sum
- autorest/adal/token.go
- autorest/adal/token_test.go
There's a security issue in jwt-go and the project appears to be
abandoned.  While we don't use the vulnerable functionality, it's easier
to simply remove our dependency.
Note that jwt-go is still used as part of tests.
> Remove runtime dependency on jwt-go

- CHANGELOG.md
- autorest/go.mod
- autorest/go.sum
- autorest/sender.go
The change to support TLS renegotiation types inadvertently removed
sharing transports, leading to a growing number of goroutines for
workloads that create a lot of different clients.
Create senders per TLS renegotiation type.  Each sender is created on
demand and cached for reuse.
> Reuse senders

- autorest/adal/token.go
- autorest/adal/token_1.13.go
- autorest/adal/token_legacy.go
- autorest/error.go
- autorest/utility.go
- autorest/utility_1.13.go
- autorest/utility_1.13_test.go
- autorest/utility_legacy.go
- autorest/utility_test.go
The refresh methods on MultiTenantServicePrincipalToken didn't properly
wrap the inner error, so as a result the check for TokenRefreshError
would fail leading to retries on a credential that would always fail.
Updated the methods to use %w to wrap the error.
Added Unwrap() method to DetailedError
Updated IsTokenRefreshError() to use errors.As() to walk the error
chain.
Legacy versions for consumers on earlier versions of Go have been
provided.  In these implementations the TokenRefreshError isn't wrapped
to avoid the hang at a loss of error information.
> Walk error chain when checking for TokenRefreshError

- autorest/azure/auth/auth.go
- autorest/azure/auth/go.mod
- autorest/azure/auth/go.sum
Added field AuxTenants to ClientCertificateConfig type, allowing for
certificate-based authorization across multiple tenants.
This builds on new functionality in the latest adal module.
> Add multi-tenant certificate auth support

- autorest/validation/validation.go
Set validation.Disabled to true to globally disable param validation.
This is an escape hatch to work around bugs in param validation.
> Add flag to disable parameter validation

- autorest/adal/token.go
- autorest/adal/token_test.go
Handle expires_on time stamps that omit an AM/PM designation.
> Fix parsing of expires_on

- autorest/adal/token.go
- autorest/adal/token_test.go
ADFS can return an empty expires_on, handle it.
Return a TokenRefreshError when failing to parse a token response.
> Handle empty expires_on

- autorest/azure/async.go
To be used for mocking Future response types.
> Add FutureAPI interface type

- autorest/azure/azure.go
- autorest/azure/azure_test.go
---
This commit fixes a panic within `WithErrorUnlessStatusCode` when the response returns a literal value of `null`:
```
:status: 202
cache-control: no-cache
pragma: no-cache
content-length: 4
content-type: application/json; charset=utf-8
expires: -1
location: https://management.azure.com/subscriptions/00000000-0000-0000-0000-000000000000/resourceGroups/acctestRG-la-210108080034968174/providers/Microsoft.OperationalInsights/clusters/acctest-LA-210108080034968174/operationresults/00000000-0000-0000-0000-000000000000?api-version=2020-08-01
azure-asyncoperation: …
```
> azure/WithErrorUnlessStatusCode: fixing a panic when the response is a literal value `null`

- autorest/azure/azure.go
- autorest/azure/azure_test.go
Improve unmarshalling support for errors that are not OData v4
compliant.
Include raw JSON body when failing to unmarshall into ServiceError.
> Handle other ServiceError corner-cases

- autorest/adal/go.mod
- autorest/adal/go.sum
- autorest/adal/sender.go
- autorest/adal/token.go
- autorest/adal/token_1.13.go
- autorest/adal/token_legacy.go
- autorest/adal/token_test.go
This back-ports a portion of the managed identity environment detection logic from `azidentity`.  It does not add support for other managed identity environments that weren't already present in this package.
> Refactor managed identity detection logic

- autorest/adal/go.mod
- autorest/adal/go.sum
- autorest/adal/token.go
The logging of request/response bodies is explicitly opt-in via the
LogAuth setting, so that LogDebug won't disclose credential data.
> Add logging for authentication requests/responses

- autorest/adal/token.go
This will allow retry logic to kick in and also avoid up-stream panics
due to both the response and the error being nil.
> Return an error if resp and err are nil

- autorest/client.go
Proposing this change following email discussion on making it less conservative. What do you think of this change?
Now it makes me think, can we update the `DefaultRetryDuration` from 30 seconds to 15 seconds if the change above is fine?
---
> Changing default polling interval from 60 to 30

- autorest/azure/auth/go.mod
- autorest/azure/auth/go.sum
This change updates /x/crypto to the latest version to mitigate CVE-2019-11840.
> Update /x/crypto to latest version

- autorest/sender.go
-----------------------------------------------------------------
This is a small change I made that should help users of the Azure SDK debugging networking issues whenever DelayForBackoff(WithCap) is called. Normally you will have to wait until the cap is reached to actually see the error. With this change, it should be printed to the info log (assuming `AZURE_GO_SDK_LOG_LEVEL` is set at least to `Info`) before DelayForBackoff(WithCap) is called, so that potential errors can be detected quicker.
> Print error to info log before backing off

- autorest/adal/sender.go
- autorest/sender.go
Type-asserting the http.DefaultTransport can fail if it was replaced
with a custom RoundTripper.  Instead, create a new http.Transport with
the settings copied from http.DefaultTransport.
> Create a default transport

- autorest/azure/cli/token.go
> GetTokenFromCLIWithParams fixed empty error message if command invoke failed.

- autorest/preparer.go
- autorest/preparer_test.go
> URL-encode semicolons in query parameters

- logger/logger.go
The correct environment variable which is used for initializing the default logger is `AZURE_GO_SDK_LOG_LEVEL` not `AZURE_GO_AUTOREST_LOG_LEVEL` as referenced https://github.com/Azure/go-autorest/blob/master/logger/logger.go#L200
> Update comment to reference the correct env var

- autorest/azure/azure.go
Noticed from Orijtech's continuous benchmarking product "Bencher" per
https://dashboard.github.orijtech.com/benchmark/3245b8e4bbbd44a597480319aaa4b9fe
that there is a bunch of code in the wild that invokes:
fmt.Sprintf("%s", string([]byte(...)))
yet the "%s" format specifier in fmt has a purpose:
%s	the uninterpreted bytes of the string or slice
as well as using the "%c" format specifier
which led to big improvements across every dimension:
* CPU time reduction by 11+% (ns/op)
* throughput improvement by 13+% (MBs/op)
* allocations reduction by 45+% (B/op)
* number of allocations reduction by 18+% (alloc/op)
Also (*bytes.Buffer).String is invoked when "%q" or "%s" is passed in so
no need to use it.
> all: remove unnecessary string([]byte) conversion in fmt.Sprintf yet %s

- autorest/azure/environments.go
- autorest/azure/environments_test.go
- autorest/azure/testdata/test_environment_1.json
Add CosmosDB Resource Identifier
This is required for Cosmos DB dataplane operations.
> Add CosmosDB Resource Identifier

- autorest/adal/token.go
- autorest/adal/token_1.13.go
- autorest/adal/token_legacy.go
- autorest/adal/token_test.go
Assume IMDS when other env vars aren't set.  If the request fails,
regular retry logic will kick in.
Bump up the health check probe to two seconds.
> Remove IMDS probe when determining environment

- autorest/azure/auth/auth.go
- autorest/azure/auth/go.mod
- autorest/azure/auth/go.sum
Getting an authorizer from MSI no longer automatically probes to see if
the endpoint is available.  We do the probe up front before the request.
> Move IMDS probe to GetAuthorizer

- autorest/azure/auth/README.md
> Add auth README

- autorest/azure/environments.go
- autorest/azure/environments_test.go
- autorest/azure/testdata/test_environment_1.json
ref: https://docs.microsoft.com/en-us/azure/key-vault/general/about-keys-secrets-certificates
ManagedHSM is only supported in AzurePublicCloud.
Signed-off-by: Anish Ramasekar <anish.ramasekar@gmail.com>
> Add ManagedHSM endpoint and resource id

- autorest/mocks/mocks.go
The addition of NewBodyWithBytes didn't account for reset() being called
during playback, causing the original body to be lost.
Preserve data source for []byte and string.
Renamed private vars to clarify their usage.
Fixes https://github.com/Azure/go-autorest/issues/665
> Fix byte buffer being cleared during replay

- autorest/azure/rp.go
- autorest/go.mod
- autorest/go.sum
The allows callers to get at the underlying error.
Fixes https://github.com/Azure/go-autorest/issues/683
> Wrap error when registering RP fails

- README.md
- autorest/adal/README.md
- autorest/azure/auth/README.md
> add notice about upcoming retirement

- autorest/adal/token.go
- autorest/adal/token_test.go
Unmarshal the value into an interface{} and perform the proper
conversion depending on the underlying type.
> Handle expires_on in int format

- autorest/azure/azure.go
Before fix, 'ANYSTRING+valid id' can also be parsed as valid id, that's not correct.
> Fix validation in resource id parsing

- autorest/adal/go.mod
Signed-off-by: Bernd Verst <github@bernd.dev>
This retracts a range of `adal` library versions which have errors in the handling of Token Refresh calls.
These errors can results in a huge range of subtle failures, such as inability to refresh a service principal token obtained via managed identity / MSI.
This retraction does not break builds using this particular version, but will print a warning to anyone impacted. `v0.9.20` is the first working version.
For this retraction to become effective a new release `v0.9.22` (since `v0.9.21` is the latest right now) needs to be tagged.
> Retract `adal` versions with token refresh errors

- autorest/azure/auth/auth.go
- autorest/azure/auth/auth_test.go
Currently we have to read the file config twice if we want to create an authorizer plus read other stuff from the config. This change allows getting the authorizer from an existing file settings object.
> feat: allow getting authorizer from existing file settings

- autorest/utility.go
Fixes https://github.com/Azure/go-autorest/issues/722
> Remove undefined behavior during return

- autorest/retriablerequest_1.7.go
- autorest/retriablerequest_1.8.go
When azure is responding with an error the retriable request that is generated ends up getting a non nil noOpcloser added to it with a reader interface. Ultimately this ends up sending a GET request to Azure that has a post body. As the http spec says that the body SHOULD be ignored this is not a critical error, but for people using custom transports this is problematic. It's also sending unnecessary bytes.
Example of the request being sent with an initial request: `Body:{} GetBody:<nil>`
This is the body when the same request is then retried: `Body:{Reader:} GetBody:<nil>`
I attempted to write a test for this but it turns out much of the test suite is leveraging GET with bodies in them. Inserting an error into the mocks for GET's with non-nil and non-empty request bodies broke a number …
> Stop retriable request from adding a non-nil Body
