Azure/go-autorest

CHANGELOG.md

This addresses Issue #5: Changelog is not updated with 1.1.0

update CHANGELOG.md for v1.1.0

---

.travis.yml

Taking a proactive stab at travis-ci git issue with "go get".

Update test go build to 1.5

---

CHANGELOG.md
autorest/autorest.go
autorest/azure/token.go
autorest/client.go
autorest/error.go
autorest/error_test.go
autorest/responder.go
autorest/sender.go

Added HTTP Response StatusCode to Error (when available)

---

CHANGELOG.md

v3.0.0 changelog

---

autorest/client_test.go

Added test to ensure NewClientWithUserAgent never modifies DefaultClient

---

autorest/azure/example/main.go

Very minor changes...
1. Remove Xplat Client ID since it is treated differently than other client ids
2. Pull "Resource" up so it's easy to test different audience URLs.
2. Make forcibly refreshing the token optional
CC @ahmetalpbalkan

clean up example a smidge

---

CHANGELOG.md
autorest/autorest.go
autorest/autorest_test.go
autorest/azure/azure.go
autorest/azure/azure_test.go
autorest/mocks/helpers.go
autorest/sender.go
autorest/sender_test.go
autorest/utility_test.go

Handle Azure long-running operations

---

autorest/azure/async.go
autorest/azure/async_test.go

Corrected DoPollForAsynchronous to not return an error when succeeding

---

CHANGELOG.md
autorest/date/date.go
autorest/date/date_test.go
autorest/date/time.go
autorest/date/time_test.go

Enabled JSON and non-JSON handling of Dates and Times

---

CHANGELOG.md
autorest/azure/async.go
autorest/date/timerfc1123.go
autorest/date/timerfc1123_test.go
autorest/responder.go
autorest/responder_test.go

Bug fix in ByUnmarshallingJSON and GET method polling

Fix bugs in ByUnmarshallingJSON and GET method polling

---

CHANGELOG.md
autorest/azure/async.go
autorest/azure/async_test.go

Corrected DoPollForAsynchronous to handle initial response

---

.travis.yml
CHANGELOG.md
autorest/azure/async.go
autorest/azure/async_test.go
autorest/azure/azure.go
autorest/error.go

Update Error message

---

autorest/azure/persist.go
autorest/azure/persist_test.go

azure/persist: fallback to copy if rename fails

---

README.md

Corrected Go Report Card badge

---

autorest/azure/token.go
autorest/azure/token_test.go
autorest/mocks/mocks.go

Address go-report issues.

---

autorest/azure/token_test.go

azure:token_test: replace panic with t.Fatal

---

autorest/azure/environments.go

Correct some of the existing URLs.

Add German Cloud

---

CHANGELOG.md

- Add trailing / to endpoint
- azure: add EnvironmentFromName
Regenerating SDK..

go-autorest version v7.0.7

---

CHANGELOG.md
autorest/preparer.go
autorest/preparer_test.go
autorest/utility.go
autorest/utility_test.go

Added WithMultiPartFormdata.
Added WithFile for sending file in request body.

WithMultipartFormdata and WithFile

---

CHANGELOG.md

Add support for multipart formdata - WithMultiPartFormdata()
Add support for sending file in request body - WithFile
Add RetryDuration parameter in client
Parameter validation code for SDK
To support SDK version 3.2.0-beta.

go-autorest Version v7.1.0

---

autorest/azure/environments.go
autorest/azure/environments_test.go

Add ASM and ARM VM DNS suffixes

---

autorest/azure/token.go
autorest/mocks/mocks.go

Fixing [PR99](https://github.com/Azure/go-autorest/pull/99) CI

Fixes golint errors

---

CHANGELOG.md

Correct version number

---

glide.lock

Before we release the new minor version, I figured we'd update our dependencies.

Updating dependencies.

---

autorest/azure/environments.go
autorest/azure/environments_test.go

(USgov, China and Germany missing)
Related to [issue 102](https://github.com/Azure/go-autorest/issues/102).
Still incomplete PR.

Adding ACR suffix to pulic cloud env

---

.travis.yml
autorest/version.go

GAS tool inspects source code for security problems, see more details at https://github.com/GoASTScanner/gas.

Add the GAS security scanner to the build steps

---

.travis.yml

CI uses go 1.8 only

---

autorest/utils/auth.go
autorest/utils/commit.go

PTAL ! @jhendrixMSFT @marstr 
For shorter samples, and avoid copypasting code.
Added funcs:
GetCommit
GetAuthorizer
GetEnvVarOrExit

Added utils package

---

autorest/client.go
autorest/sender.go
autorest/sender_test.go

Fixes https://github.com/Azure/azure-sdk-for-go/issues/588
PTAL @jhendrixMSFT  @marstr

Retry with 429 status code

---

autorest/validation/validation.go
autorest/validation/validation_test.go

Resubmitting a straight-forward PR I botched from @allencloud.
Find the former PR here: #159

Apply validation changes

---

autorest/adal/token.go
autorest/adal/token_test.go

this update is to accommodate the breaking change is MSI agent.

added metadata header when msi is used

---

GNUmakefile

Adding a Makefile as discussed in #162. This is based heavily on the [one in the Terraform AzureRM Provider repository](https://github.com/terraform-providers/terraform-provider-azurerm/blob/master/GNUmakefile) - and is _slightly_ opinionated (like formatting when building code) - but seems to work :)
Examples:
```
$ make
gofmt -w ./autorest/
go install ./autorest/
```
```
$ make build
gofmt -w ./autorest/
go install ./autorest/
```
```
$ make vet
go vet .
autorest/adal/devicetoken.go:153: wrong number of args for format in Errorf call: 2 needed but 3 args
exit status 1
Vet found suspicious constructs. Please check the reported constructs
and fix them if necessary before submitting the code for review.
make: *** [vet] Error 1
```
```
$ git checkout -- autorest/adal/
$ make vet
go vet . …
```

Adding a Makefile

---

.travis.yml
autorest/validation/validation.go

Add go 1.9 to CI

---

.travis.yml
autorest/azure/azure.go
autorest/azure/azure_test.go
autorest/validation/validation.go

Adding a little polish before this goes into `master`.

Updating tests and simplifying method.

---

autorest/client.go
autorest/client_test.go

Fixes autorest tests with cookies
PTAL
@jhendrixMSFT @marstr

Creating cookiejar while creating client

---

.github/PULL_REQUEST_TEMPLATE.md

Adding a checklist that will appear as part of any new PR, see https://github.com/Azure/azure-rest-api-specs as an example.

Adding a GitHub pull request template.

---

autorest/azure/environments.go
autorest/azure/environments_test.go
autorest/azure/testdata/test_environment_1.json

Refactoring the changes in #178, adding tests.
---

Add azure stack

---

CHANGELOG.md
autorest/azure/async.go
autorest/azure/async_test.go
autorest/azure/environments.go
autorest/azure/environments_test.go
autorest/azure/rp.go
autorest/azure/testdata/test_environment_1.json

v9.2.0, merge dev into master

---

CHANGELOG.md
autorest/adal/config.go
autorest/adal/token.go
autorest/authorization.go
autorest/client.go
autorest/sender.go

Validate credential parameters.
Don't retry on http.StatusUnauthorized.

Fix hangs during failed authentication.

---

autorest/authorization.go
autorest/authorization_test.go
autorest/preparer.go

Add api key authorization support

---

autorest/adal/README.md
autorest/adal/token.go
autorest/adal/token_test.go

feature: support username password auth

---

autorest/adal/README.md
autorest/adal/token.go
autorest/adal/token_test.go

Add support for OAuth2 Authorization Code flow for authentication. ( https://docs.microsoft.com/en-us/azure/active-directory/develop/active-directory-protocols-oauth-code )

Add support for authorization code authentication

---

CHANGELOG.md
autorest/azure/environments.go

Use US Gov AAD Endpoint for US Gov environment

---

CHANGELOG.md
autorest/azure/environments.go
autorest/azure/environments_test.go

fix the service bus suffix and add the service bus aad resource uri

---

CHANGELOG.md
autorest/version.go

Update version number.

---

.travis.yml
CHANGELOG.md
autorest/azure/environments.go

Add batch management endpoints to environment.

---

README.md
autorest/adal/README.md

replaces #249 with PR directly to master.

clarify support for AAD auth lib

---

CHANGELOG.md
autorest/azure/azure.go
autorest/azure/azure_test.go
autorest/utils/auth.go

Add Azure resource ID helper

---

.travis.yml

Use binary release of dep

---

CHANGELOG.md
autorest/azure/auth/auth.go

Use log instead of fmt

---

autorest/adal/token.go

Add more status codes

---

CHANGELOG.md
autorest/azure/auth/auth.go
autorest/version.go

Fixes https://github.com/Azure/go-autorest/issues/256

Add keyvault authorizer

---

autorest/azure/cli/profile.go

~/.azure/azureProfile.json also contains user information.

add User to profile

---

.travis.yml
Gopkg.lock
autorest/azure/rp_test.go

Add Go 1.11 to CI and update dependencies

---

.travis.yml
CHANGELOG.md
Gopkg.lock
Gopkg.toml
autorest/adal/config.go
autorest/adal/config_test.go
autorest/adal/token.go
autorest/adal/token_test.go
autorest/azure/async.go
autorest/azure/async_test.go
autorest/azure/auth/auth.go
autorest/azure/cli/token.go
autorest/azure/rp_test.go
autorest/client.go
autorest/client_test.go
autorest/sender.go
autorest/sender_test.go
logger/logger.go
logger/logger_test.go
version/version.go

merge master into dev

---

CHANGELOG.md
autorest/azure/async.go
autorest/version.go

If the provided context already has a deadline don't add the default
deadline.

Respect any specified deadline in the provided context

---

CHANGELOG.md
Gopkg.lock
Gopkg.toml
autorest/azure/environments.go
autorest/version.go

- fix DNS endpoint for ACR
- Add Cosmos DB endpoint
Fixes #366

Add CosmosDb endpoint and fix ACR endpoints for Gov Clouds

---

autorest/sender.go
autorest/sender_test.go

RFC specifies Retry-After header can be integer value expressing seconds
or an HTTP-Date indicating when to try again.
Removed superfluous check for HTTP status code.

Support HTTP-Date in Retry-After header

---

azure-pipelines.yml

add yaml file for azure devops CI

---

README.md

add status badge for azure devops CI

---

autorest/adal/persist_test.go
azure-pipelines.yml

enable build and test on linux

---

azure-pipelines.yml

Break monolithic script into separate scripts with useful names.
Moved formatting checks to the end with succeededOrFailed conditions.

Refactor azure devops pipeline

---

azure-pipelines.yml

remove unnecessary trigger section from devops

---

azure-pipelines.yml

enhance CI reporting

---

autorest/adal/go.mod
autorest/adal/go.sum

update adal module dependencies

---

autorest/adal/token_test.go
autorest/authorization_storage.go

This PR picks up two dropped error variables.

Fix Dropped Errors

---

autorest/adal/go.mod
autorest/adal/go.sum

Fixes https://github.com/Azure/go-autorest/issues/491

update adal crypto dependency

---

autorest/adal/token.go

Duration order consistency when multiplying number by time unit

---

CHANGELOG.md
autorest/sender.go
autorest/sender_test.go
autorest/utility.go
version/version.go

Bugfixes v11.1

---

CHANGELOG.md
autorest/adal/token.go
autorest/adal/token_test.go
autorest/authorization_test.go
autorest/preparer_test.go
autorest/version.go
azure-pipelines.yml

Fix race condition when refreshing token.
Fixed some tests to work with Go 1.14.
Updated CI to run latest two versions of Go.

Misc fixes and updated CI

---

CHANGELOG.md
autorest/adal/token_test.go
autorest/authorization.go
autorest/authorization_test.go
autorest/preparer_test.go
autorest/version.go
azure-pipelines.yml

Backport of https://github.com/Azure/go-autorest/pull/521

Fix x-ms-authorization-auxiliary

---

CHANGELOG.md
autorest/version.go
doc.go

----
This change is simply to make the root package importable to enable a larger fix for ambiguous import errors.

Make the root package importable

---

autorest/azure/environments.go

Update resourceManagerVMDNSSuffix for AzureUSGovernmentCloud

---

CHANGELOG.md
autorest/azure/environments.go

to support Synapse RP in different cloud for terraform.
Environment variables got from service team

Add `SynapseEndpointSuffix` in environment variables

---

autorest/go.mod
autorest/go.sum

Update adal and mocks to latest versions

---

autorest/go.mod
autorest/go.sum

update to latest adal

---

autorest/azure/environments.go

Adding ServiceBus to the ResourceIdentifiers struct, and setting it to the values for each cloud

---

autorest/azure/azure.go
autorest/azure/azure_test.go

implement stringify on go-autorest/autorest/azure.Resource

---

autorest/azure/async.go

Restore response body on successful reads

---

autorest/adal/token.go
autorest/adal/token_test.go

Fixed spelling of clientid query param for legacy authentication
endpoint.
Removed metadata header from authentication request.
Fixed parsing of expires_on in timestamp format.
Added the endpoint in the authentication failure error message.

Fixes for IMDS authentication in app services

---

autorest/azure/auth/auth.go
autorest/azure/auth/go.mod

Add credential probe logging

---

autorest/adal/token.go
autorest/adal/token_test.go

This adds support for multi-tenant authorization using certificates.

Add multi-tenant certificate auth support

---

autorest/client.go

Update doc string for Client.RetryAttempts

---

autorest/azure/auth/auth.go
autorest/azure/auth/auth_test.go
autorest/azure/auth/go.mod
autorest/azure/auth/go.sum

Update auth to use updated managed identity detection

---

logger/logger.go

Add LogAuth classification for logging authentication

---

autorest/client.go
autorest/go.mod
autorest/go.sum

Return an error if resp and err are nil

---

autorest/adal/token.go
autorest/azure/async.go
autorest/azure/azure.go
autorest/sender.go

fixed some logging statements missing new-lines
fixed broken doc link

add some logging for LROs

---

autorest/azure/environments.go
autorest/azure/environments_test.go
autorest/azure/testdata/test_environment_1.json

Add ossRDBMSResourceId to Environment configuration.

---

autorest/adal/go.mod
autorest/adal/go_mod_tidy_hack.go
autorest/adal/token_1.13.go
autorest/adal/token_legacy.go
autorest/azure/auth/go.mod
autorest/azure/auth/go_mod_tidy_hack.go
autorest/azure/cli/go.mod
autorest/azure/cli/go_mod_tidy_hack.go
autorest/date/go.mod
autorest/date/go_mod_tidy_hack.go
autorest/date/unixtime_test.go
autorest/go.mod
autorest/go_mod_tidy_hack.go
autorest/mocks/go.mod
autorest/mocks/go_mod_tidy_hack.go
autorest/retriablerequest_1.7.go
autorest/retriablerequest_1.8.go
autorest/to/go.mod
autorest/to/go_mod_tidy_hack.go
autorest/utility_1.13.go
autorest/utility_1.13_test.go
autorest/utility_legacy.go
autorest/validation/go.mod
autorest/validation/go_mod_tidy_hack.go
azure-pipelines.yml
logger/go.mod
logger/go_mod_tidy_hack.go
tracing/go.mod
tracing/go_mod_tidy_hack.go
tracing/opencensus/go.mod

see https://github.com/Azure/go-autorest/pull/645#issuecomment-898440791

update go versions (go1.15, go1.16, go1.17)

---

autorest/azure/environments.go

source: https://docs.microsoft.com/en-us/azure/active-directory/managed-identities-azure-resources/services-support-managed-identities#azure-sql

Add SQL database resource id to environment

---

autorest/azure/environments.go

Adapted from https://github.com/Azure/azure-cli/blob/dev/src/azure-cli-core/azure/cli/core/cloud.py
Fixes
- https://github.com/Azure/go-autorest/issues/312
- https://github.com/Azure/go-autorest/issues/585
- https://github.com/Azure/go-autorest/issues/687

Update some Azure environment endpoints and resource IDs

---

autorest/adal/go.mod
autorest/adal/go.sum
autorest/azure/cli/go.mod
autorest/azure/cli/go.sum
autorest/go.mod
autorest/go.sum

Fixes https://github.com/Azure/go-autorest/issues/707

Update crypto dependency to latest version

---

autorest/adal/token.go
autorest/autorest.go
autorest/azure/auth/auth.go
autorest/azure/cli/token.go
azure-pipelines.yml

Update CI to latest Go and Ubuntu images

---

autorest/adal/go.mod
autorest/azure/auth/go.mod

Mark the adal module as deprecated

---

README.md

Add links to track 2 migration guides
